service: ecs-events

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource: "*"

functions:
  state-change:
    handler: state-change/index.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.ec2
            detail-type:
              - EC2 Instance State-change Notification
            detail:
              lastStatus:
                - STOPPED
              stoppedReason:
                - Essential container in task exited
